### ISSUE TITLE
Komentár

### ISSUE THREAD

**Issue by xkapustap** [yakuta-stu/mip-clanek#1]
Rozpracovaná verzia článku znie veľmi zaujímavo, odporúčal by som spomenutie aj protokolu [Soulseek](https://en.wikipedia.org/wiki/Soulseek) (P2P protokol na vzdialenie hudby).

Teším sa na dokončenú verziu.

**Comment by yakuta-stu** [comment]
Bohužel téma článku už je potvrzena, proto by se mi nechtělo přidávat jiné věci
